SQL JOINS TABLE

CREATE TABLE STUDENT4
(S_NO INT,
S_NAME VARCHAR(20),
S_ID INT);
INSERT INTO STUDENT4
VALUES(1,'JAGAN',1011),
      (2,'PAVAN',1012),
      (3,'MANIKANTA',1013);
      SELECT * FROM STUDENT4



CREATE TABLE MARKS5
(S_ID INT,
S_NAME VARCHAR(20),
SUBJECT VARCHAR(30),
MARKS INT);
INSERT INTO MARKS5
VALUES(1011,'JAGAN','ENGLISH',40),
      (1012,'PAVAN','ENGLISH',50),
      (1013,'MANIKANTA','ENGLISH',60);
      SELECT * FROM MARKS5


#SQL INNER JOIN APPPLY ON MARKS#

SELECT STUDENT4.S_ID,STUDENT4.S_NAME,MARKS5.SUBJECT,MARKS5.MARKS
FROM STUDENT4
INNER JOIN MARKS5 ON STUDENT4.S_ID=MARKS5.S_ID;

#SQL INNER JOIN APPLY ON STUDENT4#

SELECT STUDENT4.S_ID,STUDENT4.S_NAME,MARKS5.SUBJECT,MARKS5.MARKS
FROM MARKS5
INNER JOIN STUDENT4 ON STUDENT4.S_ID=MARKS5.S_ID;

#SQL LEFT JOIN#

SELECT STUDENT4.S_ID,MARKS5.SUBJECT
FROM STUDENT4
LEFT JOIN MARKS5 ON STUDENT4.S_NAME=MARKS5.S_NAME;


#SQL RIGHT JOIN#

SELECT STUDENT4.S_ID,MARKS5.SUBJECT
FROM MARKS5
RIGHT JOIN STUDENT4 ON STUDENT4.S_NAME=MARKS5.S_NAME;